# Generated by Django 4.0.2 on 2023-02-09 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_jobs_end_date_remove_jobs_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='moanage_email',
            new_name='manager_email',
        ),
    ]
